import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

import Titulo from "../components/titulo"
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Juan Montero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Juan</a>
        </h1>
        <nav className={styles.nav}>
          <Link href="/about" >Sobre mi</Link>
        </nav>
        <Titulo/>

      </main>
    </div>
  );
}
